name: Deploy Backend to Production

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"
            - ".github/workflows/deploy-backend.yml"

jobs:
    deploy:
        name: Deploy Backend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: backend/package-lock.json

            - name: Install dependencies
              working-directory: ./backend
              run: |
                  rm -rf node_modules
                  npm ci --production=false

            - name: Create deployment archive
              run: |
                  cd backend
                  tar -czf ../backend-deploy.tar.gz \
                    --exclude=node_modules \
                    --exclude=.env \
                    --exclude=*.log \
                    --exclude=.DS_Store \
                    .

            - name: Deploy to server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  source: "backend-deploy.tar.gz"
                  target: "/tmp/"

            - name: Execute deployment on server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      # Set deployment directory
                      DEPLOY_DIR="/home/ubuntu/actions-runner/_work/back-to-hills-2025/back-to-hills-2025/backend"

                      # Create backup of current deployment
                      if [ -d "$DEPLOY_DIR" ]; then
                        BACKUP_DIR="/home/ubuntu/backups/backend-$(date +%Y%m%d-%H%M%S)"
                        mkdir -p /home/ubuntu/backups
                        cp -r "$DEPLOY_DIR" "$BACKUP_DIR"
                      fi

                      # Extract new deployment
                      mkdir -p "$DEPLOY_DIR"
                      tar -xzf /tmp/backend-deploy.tar.gz -C "$DEPLOY_DIR"
                      rm /tmp/backend-deploy.tar.gz

                      # Install dependencies with clean slate
                      cd "$DEPLOY_DIR"
                      rm -rf node_modules package-lock.json
                      npm install --production

                      # Restart the application with PM2
                      pm2 restart backend || pm2 start ecosystem.config.js --env production
                      pm2 save
