name: Deploy React App to AWS Lightsail

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      # Step 3: Install dependencies and build the project
      - name: Install Dependencies and Build
        env:
          VITE_API_URL: ${{ secrets.API_URL }}
        run: |
          cd frontend
          npm ci
          npm run build

      # Step 4: Rename dist to unma-banglore
      - name: Rename dist to unma-banglore
        run: |
          cd frontend
          mv ./dist ./unma-banglore/

      # Step 5: Verify SSH connection
      - name: Verify SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          timeout: 60s
          script: |
            echo "SSH connection successful"
            whoami
            pwd
            ls -la

      # Step 6: Clean temporary deployment directory on Lightsail
      - name: Clean Temporary Directory on Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          timeout: 60s
          script: |
            rm -rf ~/deploy-temp
            mkdir -p ~/deploy-temp
            chmod 775 ~/deploy-temp

      # Step 7: Copy files to Lightsail using SCP
      - name: Deploy to Lightsail via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          port: 22
          source: "./frontend/unma-banglore/*"
          target: "/home/ubuntu/deploy-temp/"

      # Step 8: Deploy on Lightsail
      - name: Deploy on Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          timeout: 60s
          script: |
            echo "Deploying to web root..."
            sudo rm -rf /var/www/html/unma-banglore
            sudo mkdir -p /var/www/html/unma-banglore
            sudo cp -R ~/deploy-temp/* /var/www/html/unma-banglore
            sudo chmod -R 755 /var/www/html/unma-banglore
            sudo rm -rf ~/deploy-temp

            echo "Restarting Nginx..."
            sudo rm -rf /var/cache/nginx/*
            sudo systemctl restart nginx

            echo "Deployment completed!"
