name: Frontend CI/CD

on:
    push:
        branches: [main, develop]
        paths:
            - "frontend/**"
            - ".github/workflows/frontend.yml"
    pull_request:
        branches: [main, develop]
        paths:
            - "frontend/**"

jobs:
    build:
        name: Build and Test Frontend
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

         

            - name: Create .env file for build
              working-directory: ./frontend
              run: |
                  echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
                  echo "VITE_APP_NAME=${{ secrets.VITE_APP_NAME }}" >> .env

            - name: Build application
              working-directory: ./frontend
              run: npm run build

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-build
                  path: frontend/dist
                  retention-days: 7

    deploy:
        name: Deploy Frontend
        runs-on: self-hosted
        needs: build
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: frontend-build
                  path: ./build

            - name: Create deployment directory
              run: |
                  sudo mkdir -p /var/www/back-to-hills-frontend
                  sudo chown -R $USER:$USER /var/www/back-to-hills-frontend

            - name: Deploy to Nginx directory
              run: |
                  rm -rf /var/www/back-to-hills-frontend/*
                  cp -r ./build/* /var/www/back-to-hills-frontend/

            - name: Set proper permissions
              run: |
                  sudo chown -R www-data:www-data /var/www/back-to-hills-frontend
                  sudo find /var/www/back-to-hills-frontend -type d -exec chmod 755 {} \;
                  sudo find /var/www/back-to-hills-frontend -type f -exec chmod 644 {} \;

            - name: Test Nginx configuration
              run: sudo nginx -t

            - name: Reload Nginx
              run: sudo systemctl reload nginx

            - name: Verify deployment
              run: |
                  sleep 2
                  if systemctl is-active --quiet nginx; then
                    echo "✅ Nginx is running"
                  else
                    echo "❌ Nginx is not running"
                    exit 1
                  fi

    notify:
        name: Notify Deployment Status
        runs-on: self-hosted
        needs: [build, deploy]
        if: always()

        steps:
            - name: Deployment Success
              if: needs.deploy.result == 'success'
              run: echo "✅ Frontend deployment successful!"

            - name: Deployment Failed
              if: needs.deploy.result == 'failure'
              run: |
                  echo "❌ Frontend deployment failed!"
                  exit 1
